## 服务器配置
server:
  # 服务端口
  port: 8080

## spring 配置
spring:
  cloud:
    config:
      server:
        git:
          # 配置 Git 仓库的地址
          uri: https://gitee.com/changhr2013/micro-service-config.git
          username: changhr2013
          password:
          # config server 启动时 clone 仓库
          clone-on-start: true
          default-label: master
        health:
          repositories:
            a-foo:
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev

# 监控配置
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
endpoints:
  health:
    sensitive: false

# 注册中心-客户端配置
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka/
    registry-fetch-interval-seconds: 5
ribbon:
  ServerListRefreshInterval: 1000

# 开启基于 HTTP basic 的认证
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123

## 日志配置
# 将以下包的日志设置为DEBUG，就可打印 config server 请求 Git 仓库的细节
logging:
  path: /home/microservice/log/
  file: microservice-config-server.log
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
