server:
  # 服务端口
  port: 8080
spring:
  application:
    # 服务名称
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # 配置 Git 仓库的地址
          uri: https://gitee.com/changhr2013/micro-service-config.git
          username: changhr2013
          password:
          # config server 启动时 clone 仓库
          clone-on-start: true
          default-label: master
        health:
          repositories:
            a-foo:
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev

# 健康检查
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
endpoints:
  health:
    sensitive: false

# 注册中心
eureka:
  client:
    service-url:
      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    # 表示将自己的 IP 注册到 Eureka Server
    prefer-ip-address: true

# 将以下包的日志设置为DEBUG，就可打印 config server 请求 Git 仓库的细节
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG

encrypt:
  key: foo

# 开启基于 HTTP basic 的认证
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123