## 服务器配置
server:
  port: 8040

## spring 配置
spring:
  application:
    name: microservice-gateway-zuul

## 注册中心-客户端配置
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka/

# 监控配置
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

endpoints:
  health:
    sensitive: false

## Ribbon 负载均衡配置
ribbon:
  eureka:
    # 为 ribbon 禁用 Eureka
    enabled: false
  ConnectTimeout: 3000
  ReadTimeout: 50000
  # ribbon 缓存时间
  ServerListRefreshInterval: 1000

# 各个服务负载均衡配置
microservice-provider-user:
  ribbon:
    listOfServers: provider-user-pro1:8000, provider-user-pro2:8001

microservice-consumer-movie:
  ribbon:
    listOfServers: consumer-movie-pro:8010

microservice-file-upload:
  ribbon:
    listOfServers: file-upload:8050

## Hystrix 熔断设置
# 上传大文件得将超时时间设置长一些，否则会报超时异常。
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

# Zuul 网关配置
zuul:
  # 1. 自定义指定微服务的访问路径
  routes:
    # a. 文件上传服务
    microservice-file-upload:
      path: /file/**
      service-id: microservice-file-upload
    # b. 用户中心
    microservice-provider-user:
      path: /user/**
      service-id: microservice-provider-user
    # c. 电影中心
    microservice-consumer-movie:
      path: /movie/**
      service-id: microservice-consumer-movie


  # 2. 忽略指定微服务
#  ignored-services: microservice-provider-user,microservice-consumer-movie
  # 3. 忽略所有微服务，只路由指定微服务
  # 使用 '*' 可忽略所有微服务
#  ignored-services: '*'
#  routes:
#    microservice-provider-user: /user/**
  # 同时指定微服务的 serviceId 和对应路径
#  routes:
    # 该配置方式中，user-route 只是给路由一个名称，可以任意起名。
#    user-route:
#      service-id: provider-microservice-user
      # service-id 对应的路径
#      path: /user/**

## 日志配置
logging:
  path: /home/microservice/log/
  file: microservice-gateway-zuul.log