server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  instance:
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    # 定时刷新本地缓存时间，5秒
    registry-fetch-interval-seconds: 5

# 健康检查
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
endpoints:
  health:
    sensitive: false

# 为 ribbon 禁用 Eureka
ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 3000
  ReadTimeout: 50000
  # ribbon 缓存时间
  ServerListRefreshInterval: 2000

# 各个服务负载均衡配置
microservice-provider-user:
  ribbon:
    listOfServers: peer1:8000, peer1:8001

microservice-consumer-movie:
  ribbon:
    listOfServers: peer1:8010

microservice-file-upload:
  ribbon:
    listOfServers: peer1:8050

# 上传大文件得将超时时间设置长一些，否则会报超时异常。
# 以下几行超时设置来自 http://cloud.spring.io/spring-cloud-static/Camden.SR4/#_uploading_files_through_zuul
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

# Zuul 配置
zuul:
  # 1. 自定义指定微服务的访问路径
  routes:
    # a. 文件上传服务
    microservice-file-upload:
      path: /file/**
      service-id: microservice-file-upload
    # b. 用户中心
    microservice-provider-user:
      path: /user/**
      service-id: microservice-provider-user
    # c. 电影中心
    microservice-consumer-movie:
      path: /movie/**
      service-id: microservice-consumer-movie


  # 2. 忽略指定微服务
#  ignored-services: microservice-provider-user,microservice-consumer-movie
  # 3. 忽略所有微服务，只路由指定微服务
  # 使用 '*' 可忽略所有微服务
#  ignored-services: '*'
#  routes:
#    microservice-provider-user: /user/**
  # 同时指定微服务的 serviceId 和对应路径
#  routes:
    # 该配置方式中，user-route 只是给路由一个名称，可以任意起名。
#    user-route:
#      service-id: provider-microservice-user
      # service-id 对应的路径
#      path: /user/**