spring:
  application:
    # 指定注册到 Eureka Server 上的应用名称
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  # 指定数据源
  datasource:
    # 指定数据源类型
    platform: h2
    # 指定 h2 数据库的建表脚本
    schema: classpath:schema.sql
    # 指定 h2 数据库的数据脚本
    data: classpath:data.sql

# 健康检查
management:
  endpoint:
    health:
      show-details: always

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
#      default-zone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
        default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    # 表示将自己的 IP 注册到 Eureka Server
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

---
spring:
     profiles: balance1
server:
  port: 8000

---
spring:
     profiles: balance2
server:
  port: 8001