server:
  port: 8050
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      # 默认 1M
      max-file-size: 200Mb
      # 默认 10M
      max-request-size: 250Mb
      enabled: true
eureka:
  client:
    service-url:
      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    # 定时刷新本地缓存时间
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10

ribbon:
  # ribbon 缓存时间
  ServerListRefreshInterval: 2000