server:
  port: 8010
  ## 服务器 undertow 配置
  undertow:
    max-http-post-size: 0
    # 设置I/O线程数，它主要执行非阻塞的任务，它们会负责多个连接，默认设置每个CPU核心一个线程，数量和CPU内核数目一样即可
    io-threads: 4
    # 阻塞任务线程池，当执行类似Servlet请求阻塞操作，undertow会从这个线程池中取得线程，它的值设置取决于系统的负载 io-threads * 8
    worker-threads: 32
    # 以下的配置会影响buffer，这些buffer会用于服务器连接的I/O操作，有点类似netty的池化内存管理
    # 每块buffer的空间大小，越小的空间被利用越充分
    buffer-size: 1024
    # 每个区分配的buffer数量，所以pool的大小是buffer-size * buffers-per-region
    # buffers-per-region: 1024 这个参数不需要写了
    # 是否分配的直接内存
    direct-buffers: true

spring:
  # 配置链路追踪的采样率
  sleuth:
    sampler:
      percentage: 1.0
  # zipkin 客户端配置
  zipkin:
    rabbitmq:
      queue: zipkin

## 注册中心客户端配置
eureka:
  client:
    # 设为true，开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    # 定时刷新本地缓存时间，5秒
    registry-fetch-interval-seconds: 5
  instance:
    # 表示将自己的 IP 注册到 Eureka Server
    prefer-ip-address: true
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10

## 健康检查
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
endpoints:
  health:
    sensitive: false

## 远程调用
feign:
  hystrix:
    # 说明：请务必注意，从Spring Cloud Dalston开始，Feign默认是不开启Hystrix的。
    # 因此，如使用Dalston请务必额外设置属性：feign.hystrix.enabled=true，否则断路器不会生效。
    # 而在 Spring Cloud Angel/Brixton/Camden中，Feign默认都是开启Hystrix的。无需设置该属性。
    enabled: true
  ## 请求压缩
  compression:
    request:
      enabled: true
      # 支持的媒体类型列表
      mime-types: text/xml,application/xml,application/json
      # 请求的最小阈值
      min-request-size: 2048
    response:
      enabled: true

## 日志
logging:
  level:
    # 将 Feign 接口的日志级别设置成 DEBUG，因为 Feign 的 Logger.Level 只对 DEBUG 作出响应
    com.changhr.cloud.consumer.movie.user.feign.UserFeignClient: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG