spring:
  profiles:
    active: peer1
  application:
    name: microservice-discovery-eureka

#security:
#  basic:
#    # 开启基于 HTTP basic 的认证
#    enabled: false
#  user:
#    # 配置登录的账号是 user
#    name: user
#    # 配置登录的密码是 password123
#    password: password123
#

management:
  security:
    enabled: false

endpoints:
  health:
    sensitive: false

eureka:
  server:
    # 中小规模下，自我保护模式坑比好处多，所以关闭它
    enable-self-preservation: false
    # 心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
    renewal-threshold-update-interval-ms: 120000
    # 主动失效检测间隔，配置成5秒
    eviction-interval-timer-in-ms: 5000
    # 禁用 readOnlyCacheMap
    use-read-only-response-cache: false
  instance:
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 15
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
  # 禁用 Eureka 客户端自己注册自己
#    register-with-eureka: false
#    fetch-registry: false
---

spring:
  # 指定 profile = peer1
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    # 指定当 profile = peer1 时，主机名是 peer1
    hostname: peer1
  client:
    service-url:
      # 将自己注册到 peer2 这个 Eureka 上面去
      default-zone: http://peer2:8762/eureka/

---

spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-zone: http://peer1:8761/eureka/