## 服务器配置
server:
  # 容器端口
  port: 8031

## 监控配置
management:
  port: 8032

## spring 配置
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: 192.168.40.192
    port: 5672
    username: rabbitmq
    password: rabbitmq

## 注册中心-客户端配置
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    # 务必跟 server.port 的配置保持一致
    non-secure-port: 8031
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

## 日志配置
logging:
  path: /home/microservice/log/
  file: microservice-hystrix-turbine.log

#turbine:
#  app-config: microservice-consumer-movie
#  cluster-name-expression: "'default'"