server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie
  rabbitmq:
    host: peer1
    port: 5672
    username: rabbitmq
    password: rabbitmq

# 健康检查
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
endpoints:
  health:
    sensitive: false

# 注册中心
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      # 自定义的元数据，key/value 都可以随便写
      my-metadata: service-movie

## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

# 属性配置Ribbon的负载均衡
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    # 说明：请务必注意，从Spring Cloud Dalston开始，Feign默认是不开启Hystrix的。
    # 因此，如使用Dalston请务必额外设置属性：feign.hystrix.enabled=true，否则断路器不会生效。
    # 而在 Spring Cloud Angel/Brixton/Camden中，Feign默认都是开启Hystrix的。无需设置该属性。
    enabled: true
  compression:
    request:
      enabled: true
      # 支持的媒体类型列表
      mime-types: text/xml,application/xml,application/json
      # 请求的最小阈值
      min-request-size: 2048
    response:
      enabled: true
logging:
  level:
    # 将 Feign 接口的日志级别设置成 DEBUG，因为 Feign 的 Logger.Level 只对 DEBUG 作出响应
    com.changhr.cloud.consumer.movie.user.feign.UserFeignClient: DEBUG
