server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      default-zone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true

user:
  userServiceUrl: http://localhost:8000/
