## 服务器配置
server:
  port: 9411

## spring 配置
spring:
  application:
    name: zipkin-server

## zipkin 配置
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.40.192:5672
      password: rabbitmq
      username: rabbitmq
      queue: zipkin
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://192.168.40.192:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1

## 注册中心-客户端配置
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15